[package]
name = "dip_desktop"
version = "0.1.0"
authors = ["Junichi Sugiura"]
edition = "2021"
description = "Multi-platform Text editor purely written in Rust, supercharged by Bevy game engine and Dioxus UI framework."
license = "MIT OR Apache-2.0"
repository = "https://github.com/JunichiSugiura/dip/"
homepage = "https://dipeditor.com"
documentation = "https://github.com/JunichiSugiura/dip/"
keywords = ["text", "editor", "IDE", "vi", "vim"]

[dependencies]
bevy = { version = "0.7", default-features = false }
bevy_dioxus = "0.1.1"
dioxus = "0.2"
dip_core = { version = "^0.1", path = "../core" }
